### PR TITLE
Prevent null characters from getting into SQLite

### LINKED ISSUE #2273: Crash in list command
### Brief description of your issue

I upgraded from v1.3.1251-preview to v1.31681 (rc1) and winget now crashes. 

I tried other versions - v1.3.1391-preview works but v1.3.1611-preview fails.

The failure occurs when the program examined the installed programs e.g. list command.

The same or very similar failure occurred in earlier versions of the program I tried on this installation; v1.3.1251-preview was the first version I tried that was able to list installed programs.  So it appears that v1.3.1611-preview has regressed and the correction included in v1.3.1251-preview seems to have been lost. 

### Steps to reproduce

The crash occurs on one particular machine whenever a list command is issued.

### Expected behavior

A list of installed programs displayed.

### Actual behavior

The crash is an access violation and is reported in Security and Maintenance with the following details listed:

```
Faulting application name: winget.exe, version: 1.18.2206.10001, time stamp: 0x62a3cb5a
Faulting module name: WindowsPackageManager.dll, version: 1.18.2206.10001, time stamp: 0x62a3cb32
Exception code: 0xc0000005
Fault offset: 0x0000000000146d0d
Faulting process id: 0x52b8
Faulting application start time: 0x01d88637bf09aae0
Faulting application path: C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.18.1611.0_x64__8wekyb3d8bbwe\winget.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.18.1611.0_x64__8wekyb3d8bbwe\WindowsPackageManager.dll
Report Id: 9bcc9e14-9e17-45d2-8ff4-cfaca593645c
Faulting package full name: Microsoft.DesktopAppInstaller_1.18.1611.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: winget
```

The log ends:
```
...
2022-06-22 13:58:23.228 [REPO] Creating PredefinedInstalledSource with filter [None]
2022-06-22 13:58:23.228 [REPO] Creating new SQLite Index [4294967295.4294967295] at ':memory:'
2022-06-22 13:58:23.228 [SQL ] Opening SQLite connection: ':memory:' [6, 0]
2022-06-22 13:58:23.268 [REPO] Examining ARP entries for Machine | X64
2022-06-22 13:58:23.296 [REPO] Examining ARP entries for Machine | X86
2022-06-22 13:58:23.341 [REPO] Examining ARP entries for User | X64
2022-06-22 13:58:23.345 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(192)\WindowsPackageManager.dll!00007FFBF9DD0BD5: (caller: 00007FFBF9DCA0D1) Exception(1) tid(2238) 800700B7 Cannot create a file when that file already exists.
2022-06-22 13:58:23.345 [REPO] Ignoring duplicate ARP entry User|X64|SumatraPDF [SumatraPDF]
2022-06-22 13:58:23.615 [REPO] Opening SQLite Index for ReadWrite at 'C:\Users\msajk\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\StoreEdgeFD\installed.db'
2022-06-22 13:58:23.615 [SQL ] Opening SQLite connection: 'C:\Users\msajk\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\StoreEdgeFD\installed.db' [2, 0]
2022-06-22 13:58:23.616 [REPO] Opened SQLite Index with version [1.4], last write [2022-03-12 16:23:31.000]
2022-06-22 13:58:23.664 [REPO] Opening SQLite Index for ReadWrite at 'C:\Users\msajk\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Microsoft.Winget.Source_8wekyb3d8bbwe\installed.db'
2022-06-22 13:58:23.664 [SQL ] Opening SQLite connection: 'C:\Users\msajk\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Microsoft.Winget.Source_8wekyb3d8bbwe\installed.db' [2, 0]
2022-06-22 13:58:23.665 [REPO] Opened SQLite Index with version [1.4], last write [2022-06-17 16:18:39.000]
2022-06-22 13:58:23.727 [REPO] Did not find a Version {  }
2022-06-22 13:58:23.727 [REPO] Did not find a Version {  }
```

The log from a successful run is the same but continues:
```
...
2022-06-22 13:59:37.310 [REPO] Creating PredefinedInstalledSource with filter [None]
2022-06-22 13:59:37.310 [REPO] Creating new SQLite Index [4294967295.4294967295] at ':memory:'
2022-06-22 13:59:37.310 [SQL ] Opening SQLite connection: ':memory:' [6, 0]
2022-06-22 13:59:37.348 [REPO] Examining ARP entries for Machine | X64
2022-06-22 13:59:37.373 [REPO] Examining ARP entries for Machine | X86
2022-06-22 13:59:37.414 [REPO] Examining ARP entries for User | X64
2022-06-22 13:59:37.416 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(192)\WindowsPackageManager.dll!00007FFBF8CFBF45: (caller: 00007FFBF8CF7A01) Exception(1) tid(43fc) 800700B7 Cannot create a file when that file already exists.
2022-06-22 13:59:37.417 [REPO] Ignoring duplicate ARP entry User|X64|SumatraPDF [SumatraPDF]
2022-06-22 13:59:37.706 [REPO] Opening SQLite Index for ReadWrite at 'C:\Users\msajk\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\StoreEdgeFD\installed.db'
2022-06-22 13:59:37.706 [SQL ] Opening SQLite connection: 'C:\Users\msajk\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\StoreEdgeFD\installed.db' [2, 0]
2022-06-22 13:59:37.708 [REPO] Opened SQLite Index with version [1.4], last write [2022-03-12 16:23:31.000]
2022-06-22 13:59:37.756 [REPO] Opening SQLite Index for ReadWrite at 'C:\Users\msajk\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Microsoft.Winget.Source_8wekyb3d8bbwe\installed.db'
2022-06-22 13:59:37.756 [SQL ] Opening SQLite connection: 'C:\Users\msajk\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Microsoft.Winget.Source_8wekyb3d8bbwe\installed.db' [2, 0]
2022-06-22 13:59:37.758 [REPO] Opened SQLite Index with version [1.4], last write [2022-06-17 16:18:39.000]
2022-06-22 13:59:37.814 [REPO] Did not find a Version {  }
2022-06-22 13:59:37.814 [REPO] Did not find a Version {  }
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> log from failing version stopped here...
2022-06-22 13:59:37.814 [REPO] Did not find a Version {  }
2022-06-22 13:59:37.815 [REPO] CompositeSource: The installed version of the package '' was null and is being dropped from the results.
2022-06-22 13:59:37.970 [REPO] Found multiple matches for installed package [Mozilla Firefox 101.0.1 (x64 en-US)] in source [Microsoft.Winget.Source_8wekyb3d8bbwe] when searching for [Query:[none] Include:ProductCode='mozilla firefox 101.0.1 (x64 en-us)'[Exact] Include:NormalizedNameAndPublisher='mozillafirefox'+'mozilla'[Exact]]
2022-06-22 13:59:37.971 [REPO]   Checking match with package id: Mozilla.Firefox.Beta
2022-06-22 13:59:37.971 [REPO]   Checking match with package id: Mozilla.Firefox
2022-06-22 13:59:37.971 [REPO]   Appropriate available package could not be determined
2022-06-22 13:59:38.044 [REPO] Found multiple matches for installed package [{042d26ef-3dbe-4c25-95d3-4c1b11b235a7}] in tracking catalog for source [Microsoft.Winget.Source_8wekyb3d8bbwe] when searching for [Query:[none] Include:ProductCode='{042d26ef-3dbe-4c25-95d3-4c1b11b235a7}'[Exact] Include:NormalizedNameAndPublisher='microsoftvisualc2013redistributable'+'microsoft'[Exact]]
2022-06-22 13:59:38.045 [REPO]   Checking match with package id: Microsoft.VC++2013Redist-x64
2022-06-22 13:59:38.045 [REPO]   Checking match with package id: Microsoft.VC++2013Redist-x86
...

```

### Environment

```shell
WinGet, version [1.3.1611-preview], activity [{9149E05B-F815-4315-B4BA-E72B953CD382}]
OS: Windows.Desktop v10.0.19044.1766
System Architecture: X64
Command line Args: winget  list
Package: Microsoft.DesktopAppInstaller v1.18.1611.0
```

### PR DESCRIPTION
**Pull request by JohnMcPMS**
Fixes #2273

## Issue
The root of #2273 and some previous crashes in the same area is that SQLite does not handle null characters in strings in an intuitive way.  Specifically, you can insert a string with null characters, but selecting that value out as a string results in a value that is terminates at the first null character.  However, equality comparisons against that string value in the database require the full value, including nulls, to be true.

All of this lead to the following:
1. Embedded null characters in the `DisplayVersion` of an ARP entry were read in
2. This value was inserted into the temporary database holding the system information
3. On selecting the "latest version" from the database, we select all version strings
4. With the highest version value, we select the row id back
  a. Here is where the bug strikes, the selected version string will not equal the value in the database due to the null character
5. The code rolls up to having no installed version despite explicitly being the installed database

The previous mitigation prevented the crash by simply dropping that package from `list`, but this change allows those entries to show again.

## Change
In order to prevent null characters from entering SQLite at all, the string binding functions are updated to throw if an embedded null is present.  Additionally, the consistency check is updated to detect strings with embedded null characters.

In order to prevent attempting to send null characters into the database at all, the `NormalizedString` type used throughout the manifest is updated to also replace any null characters with spaces.  This will allow those packages to be listed now.

## Validation
Added unit tests covering the changed behaviors.
Manually inserted a null character into a `DisplayVersion` registry entry on my machine:
```
PS > winget list test
No installed package found matching input criteria.
PS > wingetdev list test
Name                         Id                                     Version
------------------------------------------------------------------------------
AppInstallerTestExeInstaller {A499DD5E-8DC5-4AD2-911A-BCD0263295E9} 1.0.0.0  1
```

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-cli/pull/2289)

### CODE REVIEW

File: src/AppInstallerCLITests/CompositeSource.cpp [hunk 1]
```diff
@@ -942,3 +942,23 @@ TEST_CASE("CompositeSource_TrackingFound_NotInstalled", "[CompositeSource]")
...
+    SearchResult result = setup.Search();
+    REQUIRE(result.Matches.size() == 0);
+}
+
+TEST_CASE("CompositeSource_NullAvailableVersion", "[CompositeSource]")
+{
+    CompositeTestSetup setup{ CompositeSearchBehavior::AvailablePackages };
+    setup.Available->Everything.Matches.emplace_back(MakeInstalled(), Criteria());
+
+    // We are mostly testing to see if a null installed version causes an AV or not
```
Comment (yao-msft) [inline src/AppInstallerCLITests/CompositeSource.cpp:961]: >installed [](http://example.com/codeflow?start=46&length=9)

nit: available

**Review by yao-msft — APPROVED** [review]
:shipit:
