### PR TITLE
Change how Truncation works

### LINKED ISSUE #1300: flexible handling of GetConsoleWidth method's default value would be useful in scripting
# Description of the new feature/enhancement

When listing output ```winget``` truncates column width(s) to accommodate for the total width of the console, which is determined by a call to ```GetConsoleWidth``` in ```src\AppInstallerCLICore\TableOutput.h```

```cpp
    namespace details
    {
        // Gets the column width of the console.
        inline size_t GetConsoleWidth()
        {
            CONSOLE_SCREEN_BUFFER_INFO consoleInfo{};
            if (GetConsoleScreenBufferInfo(GetStdHandle(STD_OUTPUT_HANDLE), &consoleInfo))
            {
                return static_cast<size_t>(consoleInfo.dwSize.X);
            }
            else
            {
                return 120;
            }
        }
    }
```

If the console is not wide enough, output of a column is truncated and a UTF8 Horizontal Ellipsis (…) is append to the end of the column, also in ```src\AppInstallerCLICore\TableOutput.h```; see the first listing in the image below.

```cpp

        void OutputLineToStream(const line_t& line)
        {
            auto out = m_reporter.Info();

            for (size_t i = 0; i < FieldCount; ++i)
            {
                const auto& col = m_columns[i];

                if (col.MaxLength)
                {
                    size_t valueLength = Utility::UTF8ColumnWidth(line[i]);

                    if (valueLength > col.MaxLength)
                    {
                        size_t actualWidth;
                        out << Utility::UTF8TrimRightToColumnWidth(line[i], col.MaxLength - 1, actualWidth) << "\xE2\x80\xA6"; // UTF8 encoding of ellipsis (…) character

                        // Some characters take 2 unit space, the trimmed string length might be 1 less than the expected length.
                        if (actualWidth != col.MaxLength - 1)
                        {
                            out << ' ';
                        }

                        if (col.SpaceAfter)
                        {
                            out << ' ';
                        }
                    }
                    else
                    {
                        out << line[i];

                        if (col.SpaceAfter)
                        {
                            out << std::string(col.MaxLength - valueLength + 1, ' ');
                        }
                    }
                }
            }

            out << std::endl;
        }
```

When the console is wide enough, all of the columns are output in their entirety; see the second listing in the image below.

However, if you either pipe the output to a subsequent command, such as ```winget upgrade | Select-Object -skip 3```, or you assign it to a variable, ```GetConsoleWidth``` uses a hard coded ```120``` for the console width, because it can't get console buffer info for std out. Besides being truncated, the output is also garbled because it is not captured as UTF8; ; see the third listing in the image below.

image

# Proposed technical implementation details (optional)

Adding native PowerShell support as proposed in [#221](https://github.com/microsoft/winget-cli/issues/221) would be the ideal solution, however a quick simple patch to bump up the default value to 180+ would be great in the mean time.

```cpp
    namespace details
    {
        // Gets the column width of the console.
        inline size_t GetConsoleWidth()
        {
            CONSOLE_SCREEN_BUFFER_INFO consoleInfo{};
            if (GetConsoleScreenBufferInfo(GetStdHandle(STD_OUTPUT_HANDLE), &consoleInfo))
            {
                return static_cast<size_t>(consoleInfo.dwSize.X);
            }
            else
            {
                return 180; // or more if your heart desires 😋
            }
        }
    }
```

### LINKED ISSUE #1653: avoiding truncating search/list result
### Description of the new feature / enhancement

Currently, result of `winget list` and `winget search` is truncated for adjusting display size or 120 chars if output is redirected.
This causes the inconvenient which cannot be display full name,id,tags of apps which has long one(eg. Visual Studio family).
It cannot be avoided even if result is redirected to file because max width is currently hard coded to 120 in source if redirect.

So I'm glad if options which set max width or getting no truncated string is added(or output with another structured format like json,csv,xml?).

### Proposed technical implementation details

_No response_

### LINKED ISSUE #2161: Add '--autocolumnwidth' option
### Description of the new feature / enhancement

The current behavior of `winget` is that it looks at the first 50 output rows to determine the width of the output columns.

As a result, there are many cases where output information is truncated.

image

image

This is inconvenient, and break approaches to parse `winget`'s output such as https://gist.github.com/sba923/7924b726fd44af91d18453ee595e6548

Adding an option to trigger a behavior similar to PowerShell's `FormatTable -AutoSize` would help.

### Proposed technical implementation details

_No response_

### LINKED ISSUE #2603: Package names are being truncated when searching with empty string
### Brief description of your issue

Package name are being truncated (notice the "..." ) when you do a search with empty string: `winget search " "`

image

This issue doesn't happen when you search by part of the name
`winget search visualstudio`

image

Using Powershell x86 with maximized window on both commands

### Steps to reproduce

search with empty string: `winget search " "`

### Expected behavior

No truncated package names

### Actual behavior

Package names are being truncated

### Environment

```shell
PS C:\WINDOWS\system32> winget --version
v1.3.2691

Windows 11 22H2
```

### LINKED ISSUE #3071: Increasing terminal width doesn't address truncation
> My terminal window _was_ wide enough:
> 
> image

Is there an existing issue for this?

_Originally posted by @sba923 in https://github.com/microsoft/winget-cli/issues/3069#issuecomment-1466524470_

### LINKED ISSUE #3986: `winget search` output displays incomplete id when id is long
### Brief description of your issue

Output of `winget search` is cutting the id if it is longer and I think this wasn't the case before `1.7.3172` (I'm not completely sure about the version it appeared but I think that it was displaying full ids in the past).

When you search for a package you then most likely want to copy the id to use it to upgrade/install/... so shortening ids is bad idea IMHO.

Here is the example of `winget search terminal` output:

````
 ⚡@pavel λ winget search terminal
Name                                         Id                         Version                 Match             Source
-------------------------------------------------------------------------------------------------------------------------

Windows Terminal                             Microsoft.WindowsTerminal  1.18.3181.0             Moniker: terminal winget
Stanlys_Terminal                             Xanthus58.Stanlys_Terminal 1.0.0                                     winget
Texnomic SecureDNS Terminal                  Texnomic.SecureDNS-Termin… 0.3                                       winget
Terminals                                    Terminals.Terminals        4.0.1.0                                   winget
OpenBB Terminal                              OpenBB-finance.OpenBBTerm… 3.1.0                                     winget
Windows Terminal Preview                     Microsoft.WindowsTerminal… 1.19.3172.0                               winget
````

The output of `winget list terminal` is behaving ok - displaying full ids:

````
⚡@pavel λ winget list terminal
Name                           Id                                       Version     Available Source
----------------------------------------------------------------------------------------------------
Windows Terminal               Microsoft.WindowsTerminal                1.18.3181.0           winget
Oh My Posh version 18.26.1     JanDeDobbeleer.OhMyPosh                  18.26.1     19.2.1    winget
gsudo v2.4.1-fixnoninteractive gerardog.gsudo                           2.4.1                 winget
Tabby 1.0.200                  Eugeny.Tabby                             1.0.200     1.0.205   winget
Alacritty                      Alacritty.Alacritty                      0.12.2                winget
FileBot                        PointPlanck.FileBot                      5.1.2                 winget
Chafa                          hpjansson.Chafa                          1.12.4      1.12.5    winget
duf                            muesli.duf                               0.8.1                 winget
bottom                         Clement.bottom                           0.9.6                 winget
Fluent Terminal                53621FSApps.FluentTerminal_ce3nnjsf22cn4 0.7.7.0
Windows Terminal Preview       Microsoft.WindowsTerminal.Preview        1.19.3172.0           winget
lazygit                        JesseDuffield.lazygit                    0.40.2                winget
micro                          zyedidia.micro                           2.0.11      2.0.13    winget
````

### Steps to reproduce

`winget search terminal`

### Expected behavior

The lenght of the `id` column in `winget search` output should be determined by longest `id` value in displayed list - as it is the case for `winget list`

### Actual behavior

it seems that longer ids like `Windows.Terminal.Preview` are shortened to some artificial constant length (and comparing `winget search` and `winget list` output I think same applies for the `name` but there is some longer constant length if I'm not mistaken

### Environment

```shell
⚡@pavel λ winget --info
Windows Package Manager (Preview) v1.7.3172-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.2861
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.3172.0
```

### LINKED ISSUE #6137: `winget list` truncation is not uniform
### Relevant area(s)

WinGet CLI

### Relevant command(s)

winget list

### Brief description of your issue

I am deploying software to multiple laptops, and using `winget list` to track. However, the outputs are not consistent for the same software. 

I am executing `winget list > package_list.txt` 

Here is one example. On one laptop I see

```
Microsoft Photos                         MSIX\Microsoft.Windows.Photos_2026.1102… 2026.11020.2000…               
```

On another, I see
```
Microsoft Photos                          MSIX\Microsoft.Windows.Photos_2026.11020.… 2026.11020.2000…            
```

Why is that in the first host's output, it is truncated after `1102...` but in the second host's output it is truncated after `11020...` ? 

Similarly, here's another example
```
Microsoft Engagement Framework           MSIX\Microsoft.Services.Store.Engagemen… 10.0.23012.0                   
Microsoft Engagement Framework            MSIX\Microsoft.Services.Store.Engagement_… 10.0.23012.0                
```
On some hosts, the truncation happens after `Engagemen` (without the `t`) but on other hosts it is truncated after `Engagement` (with the `t`)

Here is another
```
Dolby Digital Plus decoder for PC OEMs   MSIX\DolbyLaboratories.DolbyDigitalPlus… 1.2.588.0                      
```
vs
```
Dolby Digital Plus decoder for PC OEMs    MSIX\DolbyLaboratories.DolbyDigitalPlusDe… 1.2.588.0                   
```

`winget list` as it is has no option to _not truncate_ when redirecting output to a file. I would atleast expect the truncation happens uniformly. 

### Steps to reproduce

It seems random, I do not know how to deterministically reproduce.

### Expected behavior

The output of `winget list` is identical in all hosts where identical softwares are installed. 

### Actual behavior

In different hosts, the same software name/version/id gets truncated at different points. 

### Environment

```shell
winget --info
Windows Package Manager v1.28.220
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.26200.8037
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.28.220.0
```

### PR DESCRIPTION
**Pull request by Trenly**
- [x] I have signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs).
- [x] I have updated the [Release Notes](../doc/ReleaseNotes.md).
- [x] This pull request is related to an issue.
  - Several, will link them after review and before merge
  - Resolves #6137
  - Resolves #1653
  - Resolves #3986
  - Resolves #3071
  - Resolves #1300
  - Resolves #2603
  - Resolves #2161
  - Related to #1618

## Problem

When winget list output is redirected to a file or variable:

 - Output was truncated at 120 characters (hardcoded fallback width)
 - Rows beyond the first 50 were truncated to widths locked by earlier rows
 - Spinner and progress bar characters appeared in the redirected output

### ChannelStreams.h / ChannelStreams.cpp

 - GetConsoleWidth() now returns std::optional<size_t> — nullopt when no console is attached (stdout redirected), actual width otherwise. Eliminates the hardcoded 120-column fallback.

### TableOutput.h

 - All rows are now buffered before any output is written. Column widths are computed from the full dataset in EvaluateAndFlushBuffer(), eliminating truncation and misalignment for both console and 
non-console output.
 - Column shrinking to fit console width is skipped when no console is present.
 - Removed the 50-row "sizing buffer" optimization that was the root cause of truncation even if the console was wide enough for all columns.

> [!NOTE]
> I assumed the 50-row sizing buffer was for performance reasons and to ensure the CLI would not take too much memory. A test on my machine showed a terminal width of 220 and roughly 200 packages. Assuming a terminal width of 500 characters on an ultrawide monitor, UTF-16 encoded, with 10k rows, that would be roughly 10 MB of buffered content. Given that 10k rows and 500 characters would be a statistical anomaly, I assumed that it would be safe to remove this sizing buffer even if it comes at a minor performance cost.

### ExecutionReporter.cpp

 - Spinner and progress bar are only created when a console is present (GetConsoleWidth().has_value()). When stdout is redirected they remain nullptr, suppressing all progress noise from redirected output.

### ExecutionProgress.cpp, WorkflowBase.cpp, ConfigurationFlow.cpp

 - Updated call sites to handle std::optional<size_t> from GetConsoleWidth().

### AppInstallerCLITests

- Added new test cases to ensure console width creates appropriate truncation behavior
- Added new test to ensure that buffering all lines at once does not cause issues

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-cli/pull/6142)

### CODE REVIEW

File: src/AppInstallerCLICore/ChannelStreams.h [hunk 1]
```diff
@@ -5,14 +5,23 @@
...
+    // Gets the current console width, or std::nullopt if stdout is not attached to a console
+    // (e.g. redirected to a file or pipe). Callers that receive nullopt should not truncate output.
+    std::optional<size_t> GetConsoleWidth();
+
+#ifndef AICLI_DISABLE_TEST_HOOKS
+    // Overrides the value returned by GetConsoleWidth(). Pass nullptr to remove the override.
+    // Pass a pointer to std::nullopt to simulate no console; pass a pointer to a value to
+    // simulate a console of that width.
+    void TestHook_SetConsoleWidth_Override(std::optional<size_t>* value);
+#endif
```
Comment (JohnMcPMS) [inline src/AppInstallerCLICore/ChannelStreams.h]: We don't put the hooks into the headers here; only the test headers.

File: src/AppInstallerCLICore/ExecutionProgress.cpp [hunk 2]
```diff
@@ -161,7 +161,7 @@ namespace AppInstaller::CLI::Execution
             }
             else
             {
-                m_out << '\r' << std::string(GetConsoleWidth(), ' ') << '\r';
+                m_out << '\r' << std::string(GetConsoleWidth().value_or(0), ' ') << '\r';
```
Comment (JohnMcPMS) [inline src/AppInstallerCLICore/ExecutionProgress.cpp]: Independent of other changes I think that it would be better to just `\n`.  Since we should never hit this if progress is disabled whenever this is `std::nullopt`, more of a nit.

File: src/AppInstallerCLITests/TableOutput.cpp [hunk 3]
```diff
@@ -0,0 +1,211 @@
...
+    Resource::LocString MakeHeader(std::string text)
+    {
+        return Resource::LocString{ LocIndString{ std::move(text) } };
+    }
+}
+
+// Test that all rows are buffered and column widths account for values beyond the first 50 rows.
+// In the old sizing-buffer design, a row at position 55 with a longer value than any of the
+// first 50 rows would be truncated. The new design buffers every row so no value is clipped.
+TEST_CASE("TableOutput_AllRowsBuffered_NoTruncation", "[tableoutput]")
```
Comment (JohnMcPMS) [inline src/AppInstallerCLITests/TableOutput.cpp:25]: All tests should set width override to prevent using the console width they are run in.

File: src/AppInstallerCLICore/ChannelStreams.h (hunk 1 above)
Comment (Trenly) [reply src/AppInstallerCLICore/ChannelStreams.h]: Removed

File: src/AppInstallerCLITests/TableOutput.cpp (hunk 3 above)
Comment (Trenly) [reply src/AppInstallerCLITests/TableOutput.cpp:25]: Added

File: src/AppInstallerCLICore/ExecutionProgress.cpp (hunk 2 above)
Comment (Trenly) [reply src/AppInstallerCLICore/ExecutionProgress.cpp]: Updated - though it does make the output a little less clean when VT is disabled:

Original: 
```
PS E:\winget-cli> git revert beda2327ff5953998fb675423c366549fd117845
PS E:\winget-cli> wingetdev search 7zip --no-vt
Name                               Id                        Version            Match         Source
----------------------------------------------------------------------------------------------------
7-Zip                              7zip.7zip                 26.00              Moniker: 7zip winget
Advanced Archive Password Recovery Elcomsoft.ArchivePassword 4.66.266.6965      Tag: 7zip     winget
NanaZip                            M2Team.NanaZip            6.0.1650.0         Tag: 7zip     winget
NanaZip Preview                    M2Team.NanaZip.Preview    6.5.1638.0         Tag: 7zip     winget
7-Zip ZS                           mcmilk.7zip-zstd          25.01 ZS v1.5.7 R4 Tag: 7zip     winget
7-Zip ZS Non Darkmode              mcmilk.7zip-zstd-ndm      25.01 ZS v1.5.7 R4 Tag: 7zip     winget
7zr                                7zip.7zr                  26.00                            winget
QNapi                              QNapi.QNapi               0.2.3              Tag: p7zip    winget
```

Updated:
```
PS E:\winget-cli> git reset --hard origin/Truncate
HEAD is now at 3a78d157 Add a test case for ensuring the spinner is not in redirected output
PS E:\winget-cli> wingetdev search 7zip --no-vt
   \
Name                               Id                        Version            Match         Source
----------------------------------------------------------------------------------------------------
7-Zip                              7zip.7zip                 26.00              Moniker: 7zip winget
Advanced Archive Password Recovery Elcomsoft.ArchivePassword 4.66.266.6965      Tag: 7zip     winget
NanaZip                            M2Team.NanaZip            6.0.1650.0         Tag: 7zip     winget
NanaZip Preview                    M2Team.NanaZip.Preview    6.5.1638.0         Tag: 7zip     winget
7-Zip ZS                           mcmilk.7zip-zstd          25.01 ZS v1.5.7 R4 Tag: 7zip     winget
7-Zip ZS Non Darkmode              mcmilk.7zip-zstd-ndm      25.01 ZS v1.5.7 R4 Tag: 7zip     winget
7zr                                7zip.7zr                  26.00                            winget
QNapi                              QNapi.QNapi               0.2.3              Tag: p7zip    winget
```

Comment (JohnMcPMS) [reply src/AppInstallerCLICore/ExecutionProgress.cpp]: Sorry, I meant "in the event that GetConsoleWidth returns `std::nullopt`, do this thing".

Comment (Trenly) [reply src/AppInstallerCLICore/ExecutionProgress.cpp]: Ahhh, that makes sense - will update

File: src/AppInstallerCLICore/ExecutionProgress.cpp [hunk 4]
```diff
@@ -161,7 +161,7 @@ namespace AppInstaller::CLI::Execution
             }
             else
             {
-                m_out << '\r' << std::string(GetConsoleWidth(), ' ') << '\r';
+                m_out << '\n';
```
Comment (JohnMcPMS) [inline src/AppInstallerCLICore/ExecutionProgress.cpp]:
```suggestion
                auto width = GetConsoleWidth();
                if (width) m_out << '\r' << std::string(width.value(), ' ') << '\r';
                else m_out << '\n';
```
But from my previous comment, since we intend to disable progress when width would be `std::nullopt`, the else is intended to never be reached.  If we ever enabled it again though, this would be what I would want (imagine a "redirected output progress" that was intended for tail viewing the file).

Comment (Trenly) [reply src/AppInstallerCLICore/ExecutionProgress.cpp]: Addressed in latest commit

**Review by JohnMcPMS — APPROVED** [review]
