### PR TITLE
Ensure Agreements don't terminate in dependency flow

### LINKED ISSUE #4233: Agreements in Dependency terminates immediately
### Brief description of your issue

When installing a package, one of it's dependencies may have an agreement which must be viewed and agreed to. When `--accept-package-agreements` is not specified, the context will terminate immediately even if interactivity is not disabled

### Steps to reproduce

`winget install Microsoft.ServiceFabricSDK`

### Expected behavior

The boolean prompt to be shown asking whether or not the user agrees to the shown agreements

### Actual behavior

The prompt is currently not shown and the context terminates

[WinGet-2024-03-06-09-17-52.790.log](https://github.com/microsoft/winget-cli/files/14511886/WinGet-2024-03-06-09-17-52.790.log)

```
Found Microsoft Azure Service Fabric SDK [Microsoft.ServiceFabricSDK] Version 7.0.1949.9590
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
This package requires the following dependencies:
  - Packages
      Microsoft.VCRedist.2015+.x64
      Microsoft.ServiceFabricRuntime
Agreements for Microsoft Azure Service Fabric [Microsoft.ServiceFabricRuntime] Version 10.0.1949.9590
Version: 10.0.1949.9590
Publisher: Microsoft Corporation
Publisher Url: https://github.com/microsoft/service-fabric
Publisher Support Url: https://github.com/microsoft/service-fabric/issues
Author: Microsoft Corporation
Homepage: https://github.com/microsoft/service-fabric
License: MIT License
License Url: https://github.com/microsoft/service-fabric/blob/master/LICENSE
Copyright: Copyright (c) Microsoft Corporation. All rights reserved.
Copyright Url: https://github.com/microsoft/service-fabric/blob/master/LICENSE
Agreements:
  End User License Agreement (EULA): https://www.microsoft.com/web/webpi/eula/net_library_eula_ENU.htm

Package agreements were not agreed to. Operation cancelled.
```

### Environment

```shell
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget --info
Windows Package Manager v1.7.10582
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.4046
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10582.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Enabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Enabled
```

### PR DESCRIPTION
**Pull request by Trenly**
- [x] I have signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs).
- [x] This pull request is related to an issue.
  - Resolves #4233 

This PR makes it so that the prompt is actually shown when a dependency contains agreements.

<details>
<summary>Manually Tested</summary>

```
PS C:\Users\Trenly> wingetdev install -m E:\winget-pkgs\manifests\m\Microsoft\ServiceFabricSDK\7.0.1949.9590
Found Microsoft Azure Service Fabric SDK [Microsoft.ServiceFabricSDK] Version 7.0.1949.9590
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
This package requires the following dependencies:
  - Packages
      Microsoft.VCRedist.2015+.x64
      Microsoft.PowerBI
      Microsoft.ServiceFabricRuntime
Agreements for Microsoft PowerBI Desktop [Microsoft.PowerBI] Version 2.130.930.0
Version: 2.130.930.0
Publisher: Microsoft Corporation
Publisher Url: https://www.microsoft.com/en-us
Publisher Support Url: https://support.microsoft.com/en-us
Author: Microsoft Corporation
Homepage: https://powerbi.microsoft.com
License: Proprietary
License Url: https://powerbi.microsoft.com/en-us/desktop-eula/
Privacy Url: https://privacy.microsoft.com/en-us/privacystatement
Copyright: Copyright (c) Microsoft Corporation. All rights reserved.
Copyright Url: https://www.microsoft.com/en-us/legal/intellectualproperty/copyright/default.aspx
Agreements:
  End User License Agreement (EULA): https://powerbi.microsoft.com/en-us/desktop-eula/

Agreements for Microsoft Azure Service Fabric [Microsoft.ServiceFabricRuntime] Version 10.0.1949.9590
Version: 10.0.1949.9590
Publisher: Microsoft Corporation
Publisher Url: https://github.com/microsoft/service-fabric
Publisher Support Url: https://github.com/microsoft/service-fabric/issues
Author: Microsoft Corporation
Homepage: https://github.com/microsoft/service-fabric
License: MIT License
License Url: https://github.com/microsoft/service-fabric/blob/master/LICENSE
Copyright: Copyright (c) Microsoft Corporation. All rights reserved.
Copyright Url: https://github.com/microsoft/service-fabric/blob/master/LICENSE
Agreements:
  End User License Agreement (EULA): https://www.microsoft.com/web/webpi/eula/net_library_eula_ENU.htm

The publisher requires that you view the above information and accept the agreements before installing.
Do you agree to the terms?
[Y] Yes  [N] No: y
(1/2) Found Microsoft PowerBI Desktop [Microsoft.PowerBI] Version 2.130.930.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
```

</details>

<details>
<summary>Works with `--disable-interactivity`</summary>

```
PS C:\Users\Trenly> wingetdev install -m E:\winget-pkgs\manifests\m\Microsoft\ServiceFabricSDK\7.0.1949.9590 --disable-interactivity
Found Microsoft Azure Service Fabric SDK [Microsoft.ServiceFabricSDK] Version 7.0.1949.9590
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
This package requires the following dependencies:
  - Packages
      Microsoft.VCRedist.2015+.x64
      Microsoft.PowerBI
      Microsoft.ServiceFabricRuntime
Agreements for Microsoft PowerBI Desktop [Microsoft.PowerBI] Version 2.130.930.0
Version: 2.130.930.0
Publisher: Microsoft Corporation
Publisher Url: https://www.microsoft.com/en-us
Publisher Support Url: https://support.microsoft.com/en-us
Author: Microsoft Corporation
Homepage: https://powerbi.microsoft.com
License: Proprietary
License Url: https://powerbi.microsoft.com/en-us/desktop-eula/
Privacy Url: https://privacy.microsoft.com/en-us/privacystatement
Copyright: Copyright (c) Microsoft Corporation. All rights reserved.
Copyright Url: https://www.microsoft.com/en-us/legal/intellectualproperty/copyright/default.aspx
Agreements:
  End User License Agreement (EULA): https://powerbi.microsoft.com/en-us/desktop-eula/

Agreements for Microsoft Azure Service Fabric [Microsoft.ServiceFabricRuntime] Version 10.0.1949.9590
Version: 10.0.1949.9590
Publisher: Microsoft Corporation
Publisher Url: https://github.com/microsoft/service-fabric
Publisher Support Url: https://github.com/microsoft/service-fabric/issues
Author: Microsoft Corporation
Homepage: https://github.com/microsoft/service-fabric
License: MIT License
License Url: https://github.com/microsoft/service-fabric/blob/master/LICENSE
Copyright: Copyright (c) Microsoft Corporation. All rights reserved.
Copyright Url: https://github.com/microsoft/service-fabric/blob/master/LICENSE
Agreements:
  End User License Agreement (EULA): https://www.microsoft.com/web/webpi/eula/net_library_eula_ENU.htm

Package agreements were not agreed to. Operation cancelled.
```

</details>
<details>
<summary>Works with `--accept-package-agreements`</summary>

```
PS C:\Users\Trenly> wingetdev install -m E:\winget-pkgs\manifests\m\Microsoft\ServiceFabricSDK\7.0.1949.9590 --accept-package-agreements
Found Microsoft Azure Service Fabric SDK [Microsoft.ServiceFabricSDK] Version 7.0.1949.9590
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
This package requires the following dependencies:
  - Packages
      Microsoft.VCRedist.2015+.x64
      Microsoft.PowerBI
      Microsoft.ServiceFabricRuntime
Agreements for Microsoft PowerBI Desktop [Microsoft.PowerBI] Version 2.130.930.0
Version: 2.130.930.0
Publisher: Microsoft Corporation
Publisher Url: https://www.microsoft.com/en-us
Publisher Support Url: https://support.microsoft.com/en-us
Author: Microsoft Corporation
Homepage: https://powerbi.microsoft.com
License: Proprietary
License Url: https://powerbi.microsoft.com/en-us/desktop-eula/
Privacy Url: https://privacy.microsoft.com/en-us/privacystatement
Copyright: Copyright (c) Microsoft Corporation. All rights reserved.
Copyright Url: https://www.microsoft.com/en-us/legal/intellectualproperty/copyright/default.aspx
Agreements:
  End User License Agreement (EULA): https://powerbi.microsoft.com/en-us/desktop-eula/

Agreements for Microsoft Azure Service Fabric [Microsoft.ServiceFabricRuntime] Version 10.0.1949.9590
Version: 10.0.1949.9590
Publisher: Microsoft Corporation
Publisher Url: https://github.com/microsoft/service-fabric
Publisher Support Url: https://github.com/microsoft/service-fabric/issues
Author: Microsoft Corporation
Homepage: https://github.com/microsoft/service-fabric
License: MIT License
License Url: https://github.com/microsoft/service-fabric/blob/master/LICENSE
Copyright: Copyright (c) Microsoft Corporation. All rights reserved.
Copyright Url: https://github.com/microsoft/service-fabric/blob/master/LICENSE
Agreements:
  End User License Agreement (EULA): https://www.microsoft.com/web/webpi/eula/net_library_eula_ENU.htm

(1/2) Found Microsoft PowerBI Desktop [Microsoft.PowerBI] Version 2.130.930.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup_x64.exe
```

</details>

<details>
<summary>Works when source agreements have not been agreed to first</summary>

```
PS C:\Users\Trenly> wingetdev install -m E:\winget-pkgs\manifests\m\Microsoft\ServiceFabricSDK\7.0.1949.9590
Found Microsoft Azure Service Fabric SDK [Microsoft.ServiceFabricSDK] Version 7.0.1949.9590
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
The `msstore` source requires that you view the following agreements before using.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
The source requires the current machine's 2-letter geographic region to be sent to the backend service to function properly (ex. "US").

Do you agree to all the source agreements terms?
[Y] Yes  [N] No: y
This package requires the following dependencies:
  - Packages
      Microsoft.VCRedist.2015+.x64
      Microsoft.PowerBI
      Microsoft.ServiceFabricRuntime
Agreements for Microsoft PowerBI Desktop [Microsoft.PowerBI] Version 2.130.930.0
Version: 2.130.930.0
Publisher: Microsoft Corporation
Publisher Url: https://www.microsoft.com/en-us
Publisher Support Url: https://support.microsoft.com/en-us
Author: Microsoft Corporation
Homepage: https://powerbi.microsoft.com
License: Proprietary
License Url: https://powerbi.microsoft.com/en-us/desktop-eula/
Privacy Url: https://privacy.microsoft.com/en-us/privacystatement
Copyright: Copyright (c) Microsoft Corporation. All rights reserved.
Copyright Url: https://www.microsoft.com/en-us/legal/intellectualproperty/copyright/default.aspx
Agreements:
  End User License Agreement (EULA): https://powerbi.microsoft.com/en-us/desktop-eula/

Agreements for Microsoft Azure Service Fabric [Microsoft.ServiceFabricRuntime] Version 10.0.1949.9590
Version: 10.0.1949.9590
Publisher: Microsoft Corporation
Publisher Url: https://github.com/microsoft/service-fabric
Publisher Support Url: https://github.com/microsoft/service-fabric/issues
Author: Microsoft Corporation
Homepage: https://github.com/microsoft/service-fabric
License: MIT License
License Url: https://github.com/microsoft/service-fabric/blob/master/LICENSE
Copyright: Copyright (c) Microsoft Corporation. All rights reserved.
Copyright Url: https://github.com/microsoft/service-fabric/blob/master/LICENSE
Agreements:
  End User License Agreement (EULA): https://www.microsoft.com/web/webpi/eula/net_library_eula_ENU.htm

The publisher requires that you view the above information and accept the agreements before installing.
Do you agree to the terms?
[Y] Yes  [N] No:
```
```
PS C:\Users\Trenly> wingetdev install -m E:\winget-pkgs\manifests\m\Microsoft\ServiceFabricSDK\7.0.1949.9590 --disable-interactivity
Found Microsoft Azure Service Fabric SDK [Microsoft.ServiceFabricSDK] Version 7.0.1949.9590
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
The `msstore` source requires that you view the following agreements before using.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
The source requires the current machine's 2-letter geographic region to be sent to the backend service to function properly (ex. "US").

One or more of the source agreements were not agreed to. Operation cancelled. Please accept the source agreements or remove the corresponding sources.
```
```
PS C:\Users\Trenly> wingetdev install -m E:\winget-pkgs\manifests\m\Microsoft\ServiceFabricSDK\7.0.1949.9590 --accept-package-agreements
Found Microsoft Azure Service Fabric SDK [Microsoft.ServiceFabricSDK] Version 7.0.1949.9590
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
The `msstore` source requires that you view the following agreements before using.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
The source requires the current machine's 2-letter geographic region to be sent to the backend service to function properly (ex. "US").

Do you agree to all the source agreements terms?
[Y] Yes  [N] No: y
This package requires the following dependencies:
  - Packages
      Microsoft.VCRedist.2015+.x64
      Microsoft.PowerBI
      Microsoft.ServiceFabricRuntime
Agreements for Microsoft PowerBI Desktop [Microsoft.PowerBI] Version 2.130.930.0
Version: 2.130.930.0
Publisher: Microsoft Corporation
Publisher Url: https://www.microsoft.com/en-us
Publisher Support Url: https://support.microsoft.com/en-us
Author: Microsoft Corporation
Homepage: https://powerbi.microsoft.com
License: Proprietary
License Url: https://powerbi.microsoft.com/en-us/desktop-eula/
Privacy Url: https://privacy.microsoft.com/en-us/privacystatement
Copyright: Copyright (c) Microsoft Corporation. All rights reserved.
Copyright Url: https://www.microsoft.com/en-us/legal/intellectualproperty/copyright/default.aspx
Agreements:
  End User License Agreement (EULA): https://powerbi.microsoft.com/en-us/desktop-eula/

Agreements for Microsoft Azure Service Fabric [Microsoft.ServiceFabricRuntime] Version 10.0.1949.9590
Version: 10.0.1949.9590
Publisher: Microsoft Corporation
Publisher Url: https://github.com/microsoft/service-fabric
Publisher Support Url: https://github.com/microsoft/service-fabric/issues
Author: Microsoft Corporation
Homepage: https://github.com/microsoft/service-fabric
License: MIT License
License Url: https://github.com/microsoft/service-fabric/blob/master/LICENSE
Copyright: Copyright (c) Microsoft Corporation. All rights reserved.
Copyright Url: https://github.com/microsoft/service-fabric/blob/master/LICENSE
Agreements:
  End User License Agreement (EULA): https://www.microsoft.com/web/webpi/eula/net_library_eula_ENU.htm

(1/2) Found Microsoft PowerBI Desktop [Microsoft.PowerBI] Version 2.130.930.0
```

</details>

<details>
<summary>Works with `--accept-source-agreements`</summary>

```
PS C:\Users\Trenly> wingetdev install -m E:\winget-pkgs\manifests\m\Microsoft\ServiceFabricSDK\7.0.1949.9590 --accept-source-agreements
Found Microsoft Azure Service Fabric SDK [Microsoft.ServiceFabricSDK] Version 7.0.1949.9590
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
The `msstore` source requires that you view the following agreements before using.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
The source requires the current machine's 2-letter geographic region to be sent to the backend service to function properly (ex. "US").

This package requires the following dependencies:
  - Packages
      Microsoft.VCRedist.2015+.x64
      Microsoft.PowerBI
      Microsoft.ServiceFabricRuntime
Agreements for Microsoft PowerBI Desktop [Microsoft.PowerBI] Version 2.130.930.0
Version: 2.130.930.0
Publisher: Microsoft Corporation
Publisher Url: https://www.microsoft.com/en-us
Publisher Support Url: https://support.microsoft.com/en-us
Author: Microsoft Corporation
Homepage: https://powerbi.microsoft.com
License: Proprietary
License Url: https://powerbi.microsoft.com/en-us/desktop-eula/
Privacy Url: https://privacy.microsoft.com/en-us/privacystatement
Copyright: Copyright (c) Microsoft Corporation. All rights reserved.
Copyright Url: https://www.microsoft.com/en-us/legal/intellectualproperty/copyright/default.aspx
Agreements:
  End User License Agreement (EULA): https://powerbi.microsoft.com/en-us/desktop-eula/

Agreements for Microsoft Azure Service Fabric [Microsoft.ServiceFabricRuntime] Version 10.0.1949.9590
Version: 10.0.1949.9590
Publisher: Microsoft Corporation
Publisher Url: https://github.com/microsoft/service-fabric
Publisher Support Url: https://github.com/microsoft/service-fabric/issues
Author: Microsoft Corporation
Homepage: https://github.com/microsoft/service-fabric
License: MIT License
License Url: https://github.com/microsoft/service-fabric/blob/master/LICENSE
Copyright: Copyright (c) Microsoft Corporation. All rights reserved.
Copyright Url: https://github.com/microsoft/service-fabric/blob/master/LICENSE
Agreements:
  End User License Agreement (EULA): https://www.microsoft.com/web/webpi/eula/net_library_eula_ENU.htm

The publisher requires that you view the above information and accept the agreements before installing.
Do you agree to the terms?
[Y] Yes  [N] No:
```

</details>

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-cli/pull/4594)

### CODE REVIEW

File: src/AppInstallerCLICore/Workflows/PromptFlow.cpp [hunk 1]
```diff
@@ -164,7 +164,7 @@ namespace AppInstaller::CLI::Workflow
                     }
                 }
 
-                EnsurePackageAgreementsAcceptance(context, /* showPrompt */ false);
+                EnsurePackageAgreementsAcceptance(context, /* showPrompt */ true);
```
Comment (yao-msft) [inline src/AppInstallerCLICore/Workflows/PromptFlow.cpp:167]: I remember the reason we set this to false was originally for winget import, winget upgrade -all etc where large numbers of packages are being processed. User needs to accept all agreements upfront rather than getting prompts repeatedly for each install. Since --disable-interactivity is implemented now, I guess it's ok'ish? Or set true/false based on the initial request? @florelis first implemented the agreements prompts. Any thoughts Flor?

Comment (Trenly) [reply src/AppInstallerCLICore/Workflows/PromptFlow.cpp:167]: As I was going through the code, it looked like this would do all the prompts up front. Although, I didn’t test the import flow. I could create an import file for a few packages with dependencies and see what happens

Comment (Trenly) [reply src/AppInstallerCLICore/Workflows/PromptFlow.cpp:167]: @yao-msft - Here is the import file I used. Notably, both `Microsoft.PowerBI` and `Microsoft.ServiceFabricRuntime` require package agreements to be accepted.

<details>
<summary>import_test.json</summary>

```json
{
	"$schema" : "https://aka.ms/winget-packages.schema.2.0.json",
	"CreationDate" : "2024-06-28T14:39:42.114-00:00",
	"Sources" : 
	[
		{
			"Packages" : 
			[
				{
					"PackageIdentifier" : "Gyan.FFmpeg"
				},
				{
					"PackageIdentifier" : "Microsoft.PowerBI"
				},
				{
					"PackageIdentifier" : "Microsoft.WingetCreate"
				},
				{
					"PackageIdentifier" : "Microsoft.ServiceFabricRuntime"
				}
			],
			"SourceDetails" : 
			{
				"Argument" : "https://cdn.winget.microsoft.com/cache",
				"Identifier" : "Microsoft.Winget.Source_8wekyb3d8bbwe",
				"Name" : "winget",
				"Type" : "Microsoft.PreIndexed.Package"
			}
		}
	],
	"WinGetVersion" : "1.9.1763-preview"
}
```

</details>
Using `wingetdev import` showed the agreements for both of the packages up front and did not require individual acceptance per-package

```raw
PS C:\Users\Trenly> wingetdev import D:\Users\Trenly\Downloads\Temp\import_test.json
Agreements for Microsoft PowerBI Desktop [Microsoft.PowerBI] Version 2.130.930.0
Version: 2.130.930.0
Publisher: Microsoft Corporation
Publisher Url: https://www.microsoft.com/en-us
Publisher Support Url: https://support.microsoft.com/en-us
Author: Microsoft Corporation
Homepage: https://powerbi.microsoft.com
License: Proprietary
License Url: https://powerbi.microsoft.com/en-us/desktop-eula/
Privacy Url: https://privacy.microsoft.com/en-us/privacystatement
Copyright: Copyright (c) Microsoft Corporation. All rights reserved.
Copyright Url: https://www.microsoft.com/en-us/legal/intellectualproperty/copyright/default.aspx
Agreements:
  End User License Agreement (EULA): https://powerbi.microsoft.com/en-us/desktop-eula/

Agreements for Microsoft Azure Service Fabric [Microsoft.ServiceFabricRuntime] Version 10.0.1949.9590
Version: 10.0.1949.9590
Publisher: Microsoft Corporation
Publisher Url: https://github.com/microsoft/service-fabric
Publisher Support Url: https://github.com/microsoft/service-fabric/issues
Author: Microsoft Corporation
Homepage: https://github.com/microsoft/service-fabric
License: MIT License
License Url: https://github.com/microsoft/service-fabric/blob/master/LICENSE
Copyright: Copyright (c) Microsoft Corporation. All rights reserved.
Copyright Url: https://github.com/microsoft/service-fabric/blob/master/LICENSE
Agreements:
  End User License Agreement (EULA): https://www.microsoft.com/web/webpi/eula/net_library_eula_ENU.htm

The publisher requires that you view the above information and accept the agreements before installing.
Do you agree to the terms?
[Y] Yes  [N] No: y
(1/4) Found FFmpeg [Gyan.FFmpeg] Version 7.0.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Command line alias added: "ffmpeg"
Command line alias added: "ffplay"
Command line alias added: "ffprobe"
Successfully installed

(2/4) Found Microsoft PowerBI Desktop [Microsoft.PowerBI] Version 2.130.930.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Successfully installed

(3/4) Found Windows Package Manager Manifest Creator [Microsoft.WingetCreate] Version 1.6.1.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
  ██████████████████████████████  100%
Successfully installed

(4/4) Found Microsoft Azure Service Fabric [Microsoft.ServiceFabricRuntime] Version 10.0.1949.9590
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
```

Comment (yao-msft) [reply src/AppInstallerCLICore/Workflows/PromptFlow.cpp:167]: Thanks for testing out @trenly Does any of the packages in the import have dependency packages that require agreements? That's the part where prompts will show up when user thought every package agreements are accepted and they leave the keyboard and let winget run.

Comment (Trenly) [reply src/AppInstallerCLICore/Workflows/PromptFlow.cpp:167]: Let me see if I can find one

Comment (Trenly) [reply src/AppInstallerCLICore/Workflows/PromptFlow.cpp:167]: It looks like `Microsoft.ServiceFabricSDK`  has `Microsoft.ServiceFabricRuntime` as a dependency which requires the use of agreements.

<details>
<summary>import_test_2.json</summary>

```json
{
	"$schema" : "https://aka.ms/winget-packages.schema.2.0.json",
	"CreationDate" : "2024-06-28T14:39:42.114-00:00",
	"Sources" : 
	[
		{
			"Packages" : 
			[
				{
					"PackageIdentifier" : "Gyan.FFmpeg"
				},
				{
					"PackageIdentifier" : "Microsoft.ServiceFabricSDK"
				},
				{
					"PackageIdentifier" : "Microsoft.WingetCreate"
				}
			],
			"SourceDetails" : 
			{
				"Argument" : "https://cdn.winget.microsoft.com/cache",
				"Identifier" : "Microsoft.Winget.Source_8wekyb3d8bbwe",
				"Name" : "winget",
				"Type" : "Microsoft.PreIndexed.Package"
			}
		}
	],
	"WinGetVersion" : "1.9.1763-preview"
}
```

</details>

However, it looks like dependencies are never attempted to be installed as part of the import flow???????

<details>
<summary>WinGet v1.9.1763-preview</summary>

```
PS C:\Users\Trenly> winget import D:\Users\Trenly\Downloads\Temp\import_test_2.json
The packages found in this import have the following dependencies:
  - Packages
      Microsoft.VCRedist.2015+.x64
      Microsoft.ServiceFabricRuntime
(1/3) Found FFmpeg [Gyan.FFmpeg] Version 7.0.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Command line alias added: "ffmpeg"
Command line alias added: "ffplay"
Command line alias added: "ffprobe"
Successfully installed

(2/3) Found Microsoft Azure Service Fabric SDK [Microsoft.ServiceFabricSDK] Version 7.0.1949.9590
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1603
Installer log is available at: C:\Users\Trenly\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Microsoft.ServiceFabricSDK.7.0.1949.9590-2024-06-28-15-17-35.155.log

(3/3) Found Windows Package Manager Manifest Creator [Microsoft.WingetCreate] Version 1.6.1.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
  ██                              7%
An unexpected error occurred while executing the command:
0x800704c7 : The operation was canceled by the user.
// Intentionally used Ctrl+C
```

</details>

<details>
<summary>wingetdev build on 6fc8a829d</summary>

```
PS C:\Users\Trenly> wingetdev import D:\Users\Trenly\Downloads\Temp\import_test.json
The packages found in this import have the following dependencies:
  - Packages
      Microsoft.VCRedist.2015+.x64
      Microsoft.ServiceFabricRuntime
(1/3) Found FFmpeg [Gyan.FFmpeg] Version 7.0.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Command line alias added: "ffmpeg"
Command line alias added: "ffplay"
Command line alias added: "ffprobe"
Successfully installed

(2/3) Found Microsoft Azure Service Fabric SDK [Microsoft.ServiceFabricSDK] Version 7.0.1949.9590
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1603
Installer log is available at: C:\Users\Trenly\AppData\Local\Packages\WinGetDevCLI_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Microsoft.ServiceFabricSDK.7.0.1949.9590-2024-06-28-15-19-52.411.log

(3/3) Found Windows Package Manager Manifest Creator [Microsoft.WingetCreate] Version 1.6.1.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
  ▌                               2%
An unexpected error occurred while executing the command:
0x800704c7 : The operation was canceled by the user.
// Intentionally used Ctrl+C
```

</details>

Comment (florelis) [inline src/AppInstallerCLICore/Workflows/PromptFlow.cpp:167]: Nit: If we do this, the `showPrompt` argument isn't needed anymore and could be removed

**Review by yao-msft — APPROVED** [review]

File: src/AppInstallerCLICore/Workflows/PromptFlow.cpp (hunk 1 above)
Comment (yao-msft) [reply src/AppInstallerCLICore/Workflows/PromptFlow.cpp:167]: Discussed offline, we'll leave this as is in case we found issues and need to revert back

Comment (yao-msft) [reply src/AppInstallerCLICore/Workflows/PromptFlow.cpp:167]: Thanks for testing. Discussed with Flor and we think we are good with the change. I'm not sure what will be the case with `winget upgrade --all` where packages to be upgraded have dependencies that require agreements. But as long as there's --accept-agreements and --disable-interactivity. There's always a workaround available.

Comment (Trenly) [reply src/AppInstallerCLICore/Workflows/PromptFlow.cpp:167]: I’m not sure either, but we can always revert this change too, if it becomes an issue. I would think dependencies in the upgrade flow are more rare though, as users would generally already have the dependency installed prior to an upgrade - unless of course the upgrade bumps the minimum version of the dependency
