### PR TITLE
Fix behavior for user settings scope preference/requirement for portable install

### LINKED ISSUE #2475: Installation of portable packages does not respect scope preference from settings.json
### Brief description of your issue

Installation of portable packages does not respect scope preference defined in the `settings.json`. Explicitly using the `--scope` parameter works, however.

### Steps to reproduce

1. Add this section in your `settings.json`:
```json
    "installBehavior": {
        "preferences": {
            "scope": "machine"
        }
    },
```
2. Install a portable package without explicitly defining the scope (e.g., `winget install yt-dlp.yt-dlp`)
3. Package is installed under user scope

### Expected behavior

It should respect the scope preference in the `settings.json`

### Actual behavior

It defaults to the user scope despite the config in the settings.

### Environment

```shell
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1194
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
```

### PR DESCRIPTION
**Pull request by ryfu-msft**
Fixes #2475

Changes:
Fixes an issue where portable installation was not taking in the installbehavior preference/requirement for scope before executing the portable installation.

Tests:
- Added settings tests for verifying install behavior scope preference/requirement
- Added E2E tests modifying the settings file with the scope preference and verifying portable install.

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://api.github.com/repos/microsoft/winget-cli/pulls/2918)

### CODE REVIEW

File: src/AppInstallerCommonCore/Manifest/ManifestCommon.cpp [hunk 1]
```diff
@@ -3,6 +3,7 @@
 #include "pch.h"
 #include "winget/ManifestCommon.h"
 #include "winget/ManifestValidation.h"
+#include "winget/UserSettings.h"
```
Comment (yao-msft) [inline src/AppInstallerCommonCore/Manifest/ManifestCommon.cpp:6]: This is not needed

File: src/AppInstallerCommonCore/Public/winget/UserSettings.h [hunk 2]
```diff
@@ -15,6 +16,7 @@
 #include <vector>
 
 #include "AppInstallerArchitecture.h"
+#include "ManifestCommon.h"
```
Comment (yao-msft) [inline src/AppInstallerCommonCore/Public/winget/UserSettings.h:19]: duplicate includes as line 8?

File: src/AppInstallerCLITests/ExperimentalFeature.cpp [hunk 3]
```diff
@@ -39,7 +39,8 @@ TEST_CASE("ExperimentalFeature ExperimentalCmd", "[experimentalFeature]")
     SECTION("Feature on")
     {
         std::string_view json = R"({ "experimentalFeatures": { "experimentalCmd": true } })";
-        SetSetting(Stream::PrimaryUserSettings, json);
+
+        (Stream::PrimaryUserSettings, json);
```
Comment (yao-msft) [inline src/AppInstallerCLITests/ExperimentalFeature.cpp:43]: unintentional change?

File: src/AppInstallerCommonCore/Public/winget/UserSettings.h [hunk 4]
```diff
@@ -242,4 +244,5 @@ namespace AppInstaller::Settings
     const UserSettings* TryGetUser();
     UserSettings const& User();
     bool TryInitializeCustomUserSettings(std::string content);
+    Manifest::ScopeEnum ConvertToScopeEnum(Settings::ScopePreference scope);
```
Comment (yao-msft) [inline src/AppInstallerCommonCore/Public/winget/UserSettings.h:247]: I think previously we had separate scope enum for settings, so we don't mix manifest concept with settings, but if we are dealing with Manifest::ScopeEnum here, should we just return Manifest::ScopeEnum directly so there's no need of SettingsScopeEnum?

**Review by yao-msft — APPROVED** [review]
