### PR TITLE
Make Symlink Target Canonical

### LINKED ISSUE #2561: [Dev] Portable In Zip does not uninstall correctly
### Brief description of your issue

When a portable installer is installed from inside a Zip installer, if a user has specified the relative path to the file with a `./` preceding it, as is commonplace when representing paths relative to a given root, the file cannot be uninstalled correctly

<details>
<summary>Details on RCA</summary>

In `./src/AppInstallerCLICore/PortableInstaller.cpp` replace the `VerifyPortableFile` function on line 56 with this:
```
    bool VerifyPortableFile(AppInstaller::Portable::PortableFileEntry& entry)
    {
        std::filesystem::path filePath = entry.GetFilePath();
        PortableFileType fileType = entry.FileType;

        if (fileType == PortableFileType::File)
        {
            SHA256::HashBuffer fileHash = SHA256::ComputeHashFromFile(filePath);
            if (std::filesystem::exists(filePath) && !SHA256::AreEqual(fileHash, SHA256::ConvertToBytes(entry.SHA256)))
            {
                AICLI_LOG(CLI, Info, << "File hash does not match ARP Entry. Expected: " << entry.SHA256 << " Actual: " << fileHash.data());
                return false;
            }
        }
        else if (fileType == PortableFileType::Symlink)
        {
            if (Filesystem::SymlinkExists(filePath) && !Filesystem::VerifySymlink(filePath, entry.SymlinkTarget))
            {
                AICLI_LOG(CLI, Info, << "Symlink target does not match ARP Entry. Expected: " << entry.SymlinkTarget << " Actual: " << std::filesystem::read_symlink(filePath).string());
                return false;
            }
        }

        return true;
    }
```

With the information the additional logging provided, I found this - 
> Symlink target does not match ARP Entry. Expected: C:\Users\Trenly\AppData\Local\Microsoft\WinGet\Packages\WindowsPostInstallWizard.UniversalSilentSwitchFinder_Microsoft.Winget.Source_8wekyb3d8bbwe\ussf.exe Actual: C:\Users\Trenly\AppData\Local\Microsoft\WinGet\Packages\WindowsPostInstallWizard.UniversalSilentSwitchFinder_Microsoft.Winget.Source_8wekyb3d8bbwe\\.\ussf.exe
</details>

### Steps to reproduce

* Run `wingetdev install ussf`
* Wait for package to install
* Run `wingetdev uninstall ussf`

### Expected behavior

Package uninstalls correctly

### Actual behavior

> Unable to remove Portable package as it has been modified; to override this check use --force

### Environment

```shell
Wingetdev built off of https://github.com/microsoft/winget-cli/commit/8a8ad84c47705971b62492808800045c6f91961f
```

### PR DESCRIPTION
**Pull request by Trenly**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Are you working against an Issue?
  - Resolves #2561 

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-cli/pull/2563)

### CODE REVIEW

File: src/AppInstallerCommonCore/Filesystem.cpp [hunk 1]
```diff
@@ -170,7 +170,7 @@ namespace AppInstaller::Filesystem
 
     bool VerifySymlink(const std::filesystem::path& symlink, const std::filesystem::path& target)
     {
-        const std::filesystem::path& symlinkTargetPath = std::filesystem::read_symlink(symlink);
+        const std::filesystem::path& symlinkTargetPath = std::filesystem::read_symlink(symlink).lexically_normal();
```
Comment (yao-msft) [inline src/AppInstallerCommonCore/Filesystem.cpp:173]: Since here it's doing direct string comparison, it would be better to use weakly_canonical to normalize the case of the path.

Also the above one(during create_symlink) can also use  weakly_canonical to get case correct.

File: src/AppInstallerCommonCore/Filesystem.cpp [hunk 2]
```diff
@@ -170,7 +170,7 @@ namespace AppInstaller::Filesystem
 
     bool VerifySymlink(const std::filesystem::path& symlink, const std::filesystem::path& target)
     {
-        const std::filesystem::path& symlinkTargetPath = std::filesystem::read_symlink(symlink).lexically_normal();
+        const std::filesystem::path& symlinkTargetPath = std::filesystem::read_symlink(symlink).weakly_canonical();
```
Comment (yao-msft) [inline src/AppInstallerCommonCore/Filesystem.cpp:173]: This will probably fail the build, it should be std::filesystem::weakly_canonical(path)

**Comment by Trenly** [comment]
RIP. I can't see which ones are failing

**Comment by yao-msft** [comment]
It's failing at VerifySymlink unit tests. I can give it a try and see if I can get a quick fix.

File: src/AppInstallerCommonCore/Filesystem.cpp [hunk 3]
```diff
@@ -152,7 +152,7 @@ namespace AppInstaller::Filesystem
 #endif
         try
         {
-            std::filesystem::create_symlink(target, link);
+            std::filesystem::create_symlink(std::filesystem::weakly_canonical(target), link);
```
Comment (yao-msft) [inline src/AppInstallerCommonCore/Filesystem.cpp:155]: After some testing, symlinks can point to relative paths, so we should probably use whatever the target value is passed in. Caller needs to canonicalize it if caller wants to.

File: src/AppInstallerCommonCore/Filesystem.cpp [hunk 4]
```diff
@@ -170,7 +170,7 @@ namespace AppInstaller::Filesystem
 
     bool VerifySymlink(const std::filesystem::path& symlink, const std::filesystem::path& target)
     {
-        const std::filesystem::path& symlinkTargetPath = std::filesystem::read_symlink(symlink);
+        const std::filesystem::path& symlinkTargetPath = std::filesystem::weakly_canonical(symlink);
         return symlinkTargetPath == target;
```
Comment (yao-msft) [inline src/AppInstallerCommonCore/Filesystem.cpp:174]: the target should be canonicalized before comparing. That should fix the issue
```suggestion
        return symlinkTargetPath == std::filesystem::weakly_canonical(target);

```

Comment (Trenly) [reply src/AppInstallerCommonCore/Filesystem.cpp]: Hopefully!

**Comment by Trenly** [comment]
You fixed it!
