### PR TITLE
Ensure available packages match with a single installed package

### LINKED ISSUE #983: Import does not work when some packages names could correspond to multiple packages.
# Brief description of your issue
winget import fail for some packages because of multiple entries that could match the name of the package.

# Steps to reproduce

Create a pacakge.json file with a package (Microsoft.Teams or Microsoft.Office) that has a name that match multple packages. 
```json
				{
					"PackageIdentifier": "Microsoft.Teams"
				}
			],
			"SourceDetails" : 
			{
				"Argument" : "https://winget.azureedge.net/cache",
				"Identifier" : "Microsoft.Winget.Source_8wekyb3d8bbwe",
				"Name" : "winget",
				"Type" : "Microsoft.PreIndexed.Package"
			}
```
Do a `winget import package.json`

# Expected behavior

Installation happen without error.

# Actual behavior

Logs can be found in this feedback: https://aka.ms/AAco2lu
image
error is in french but it basically just says Microsoft.Teams name match multiple packages.

# Environment

```none
[winget --info]
Windows Package Manager v0.4.11391
Windows: Windows.Desktop v10.0.19042.985
Package: Microsoft.DesktopAppInstaller v1.11.11391.0

Any other software?
```

### PR DESCRIPTION
**Pull request by lechacon**
When searching for installed packages matching an available package, if there were multiple matches we would create multiple results for the search. This caused commands that require a single match, like import or upgrade, to fail. Modified to select a single installed package as match if it has a strong match (product code or package family name).

This partially fixes #983 in that import and upgrade now won't fail for packages like Teams, but does not address the underlying issue of how we should deal with packages that have multiple ARP entries.

---

Also, modified dependencies code to check the experimental feature only once.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-cli/pull/1473)

### CODE REVIEW

File: src/AppInstallerRepositoryCore/CompositeSource.cpp [hunk 1]
```diff
@@ -553,14 +553,46 @@ namespace AppInstaller::Repository
...
+                                        break;
+                                    }
+                                }
+                            }
                         }
                     }
+
+                    if (installedPackage)
+                    {
+                        foundInstalledMatch = true;
```
Comment (JohnMcPMS) [inline src/AppInstallerRepositoryCore/CompositeSource.cpp:593]: The test failure is due to the single result path not ever calling `ContainsInstalledPackage`.  I'm not sure that the call to it in the multi result path is correct either.  It should probably just be moved here, as the correlation itself should not be concerned with whether another source has already correlated.

With your change, one source correlating with an installed package could lead a package that had two (and thus was ignored) suddenly having only one since one could be ignored due to a prior correlation.  It should just check all options and only succeed if a single string correlation was found.

**Review by JohnMcPMS — APPROVED** [review]

**Comment by DrCaos** [comment]
we have that problem when we want uninstall teams ;(
image

**Comment by denelon** [comment]
@lechacon, does this also address the issue with uninstall also?

**Comment by lechacon** [comment]
I think it should. The change was at the source search level, so it would affect anything that calls into it, including uninstall. I just tried it and uninstall worked for me.

@DrCaos , what version of winget are you using? (Output of `winget --info`)

**Comment by gulshan** [comment]
Also facing the multiple teams issue. `winget` cannot upgrade teams-
image
