### PR TITLE
Copy install behavior flags on upgrade --all

### LINKED ISSUE #2008: winget (v1.2) upgrade --all --silent only installs the first package silently
### Brief description of your issue

```winget upgrade --all --silent``` only installs the first package silently. The rest shows progress.

I had following upgrades available when running ```winget upgrade```.

```
Name                                               Id                                Version       Available     Source
-----------------------------------------------------------------------------------------------------------------------
Microsoft Teams                                    Microsoft.Teams                   1.5.00.2164   1.5.00.4689   winget
Microsoft Visual C++ 2015-2022 Redistributable (x… Microsoft.VC++2015-2022Redist-x86 14.31.30919.0 14.31.31103.0 winget
Microsoft Teams                                    Microsoft.Teams                   1.4.0.19572   1.5.00.4689   winget
Microsoft Visual C++ 2015-2022 Redistributable (x… Microsoft.VC++2015-2022Redist-x64 14.31.30919.0 14.31.31103.0 winget
Eclipse Temurin JDK with Hotspot 11                EclipseAdoptium.Temurin.11        11.0.12.7     11.0.14.101   winget
5 upgrades available.
```

First Teams installed silently, but neither of the VCRedist or JDK did.

### Steps to reproduce

Have more than one package to upgrade, then:

* ```winget upgrade --all --silent```

### Expected behavior

All packages should install silently.

### Actual behavior

Only the first package installs silently.

### Environment

```shell
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1586
Package: Microsoft.DesktopAppInstaller v1.17.10271.0
```

### PR DESCRIPTION
**Pull request by florelis**
*Issue:*
When we install multiple packages in the same execution (`upgrade --all` and `import`), we create a sub-context to install each individual package but this sub-context does not respect the parent's install behavior flags, like `--silent`.

*Change:*
Added a step to the creation of a sub-context to copy the relevant flags from the parent context, so that the same behavior is used for all packages. Added a test to verify the new behavior.

---

This came from a user running `winget upgrade --all --silent` and expecting all the upgrades to be done silently. We need to either respect those flags (this PR) or change the argument validation to forbid that combination.

I figure the most contentious issue with this PR will be which args we should forward. I added basically everything that made sense to me, but we can trim the list as much as needed.

Fixes #2008 and #2793

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-cli/pull/2794)

### CODE REVIEW

File: src/AppInstallerCLICore/ExecutionContext.cpp [hunk 1]
```diff
@@ -128,9 +128,41 @@ namespace AppInstaller::CLI::Execution
...
         }
+        CopyArgsToSubContext(clone.get());
         return clone;
     }
 
+    void Context::CopyArgsToSubContext(Context* subContext)
+    {
+        // Copy over install behavior flags from the parent context.
+        // Arguments not copied: Override, Log
+        for (auto flag : {
```
Comment (yao-msft) [inline src/AppInstallerCLICore/ExecutionContext.cpp:139]: Do we need to copy over some other behavior args like DisableInteractivity, Force, AcceptPackageAgreements, etc? I feel this needs a more thorough revist.

I also feel this selective copying is hard to maintain but I cannot find a better way at the moment.

Comment (florelis) [reply src/AppInstallerCLICore/ExecutionContext.cpp:139]: DisableInteractivity and AcceptPackageAgreements don't need to be copied over because those are handled at the top level. Unless we have nested contexts...

I've been thinking we can add some tags/flags about what an argument is for. Like, IsInstallBehavior, IsGlobalBehavior, IsQueryArgument. Then we could do this copying based on that, and we could also use it for argument validation. For example, Manifest cannot be used with query/source arguments, and installer specific args (like override) cannot be used when dealing with multiple packages (update --all)

Comment (yao-msft) [reply src/AppInstallerCLICore/ExecutionContext.cpp:139]: I just went over all the args, I suggest to copy over Interactive, Silent, Locale, InstallScope, InstallArchitecture, HashOverride, IgnoreLocalArchiveMalwareScan, NoUpgrade,  Force

Regarding InstallLocation, I saw in PromptForMultiplePackages we set them all to same value already, but I feel it will be more likely to cause conflicts for packages if installerss write to the InstallLocation root. Perhaps we should add a todo somewhere to revisit this. And this copy is probably not needed.

**Review by yao-msft — APPROVED** [review]
Please fix the tests before merge

File: src/AppInstallerCLICore/ExecutionContext.cpp (hunk 1 above)
Comment (Trenly) [reply src/AppInstallerCLICore/ExecutionContext.cpp:138]: @florelis / @yao-msft; Regarding this comment -
> DisableInteractivity and AcceptPackageAgreements don't need to be copied over because those are handled at the top level. Unless we have nested contexts...

I just stumbled across this issue:
- #2680

Perhaps the "top-level" flags *do* need to be copied over?
