### PR TITLE
Fall back to WinINet if DO download fails

### LINKED ISSUE #1060: Fails to update program, error 0x801901a0
# Brief description of your issue

Just got winget installed after joining the package manager beta, tried upgrade --all and it keeps dying trying to upgrade QuickPar with a Requested range not satisfiable (416) error

# Steps to reproduce

Attempt to upgrade QuickPar, would assume the same issue occurs if you try to install it from scratch but I haven't tried it
# Expected behavior

For it to download the setup and the upgrade to complete
# Actual behavior

Error on setup download

# Environment

```none
[winget --info]
Windows Package Manager version v1.0.11451
Windows: Windows.Desktop version v10.0.19043.985
Package: Microsoft.DesktopAppInstaller version v1.11.11451.0

Any other software?
```
Was running it in a PowerShell instance inside of the new Terminal, don't know if that would change anything or not

### LINKED ISSUE #1076: winget install results in 0x80d03002 : unknown error
# Brief description of your issue
winget install results in 0x80d03002 : unknown error

# Steps to reproduce
In Powershell issue the following command:
> winget install 'Visual Studio Code'

# Expected behavior

Installation of visual studio code should begin.

# Actual behavior

Found Visual Studio Code [Microsoft.VisualStudioCode]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://az764295.vo.msecnd.net/stable/054a9295330880ed74ceaedda236253b4f39a335/VSCodeUserSetup-x64-1.56.2.exe
An unexpected error occurred while executing the command:
0x80d03002 : unknown error

# Environment
Windows Package Manager v1.0.11451
Windows: Windows.Desktop v10.0.19043.985
Package: Microsoft.DesktopAppInstaller v1.11.11451.0

Any other software?
```

### PR DESCRIPTION
**Pull request by JohnMcPMS**
Resolves #1060 and resolves #1076 (well, mitigates really but that isn't a verb that GitHub responds to).

## Change
There have been several issues caused by DO being disabled by policy, or failing to redirect properly.  Due to this, and to prevent other issues from impacting users, we will fall back to the WinINet download code path when DO fails.

Some error codes are intentionally excluded from falling back, largely those pertaining to metered networks.  We will add more cases as we find them.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-cli/pull/1138)

### CODE REVIEW

File: src/AppInstallerCommonCore/AppInstallerTelemetry.cpp [hunk 1]
```diff
@@ -530,6 +530,19 @@ namespace AppInstaller::Logging
...
     }
 
+    void TelemetryTraceLogger::LogNonFatalDOError(std::string_view url, HRESULT hr) const noexcept
+    {
+        if (IsTelemetryEnabled())
+        {
+            AICLI_TraceLoggingWriteActivity(
+                "NonFatalDOError",
+                TraceLoggingUInt32(s_subExecutionId, "SubExecutionId"),
+                AICLI_TraceLoggingStringView(url, "URL"),
```
Comment (yao-msft) [inline src/AppInstallerCommonCore/AppInstallerTelemetry.cpp:540]: >URL [](http://example.com/codeflow?start=51&length=3)

Url is used as field name in above telemetry methods, we could probably save 1 small change in processing raw scripts by using same casing as previous

**Review by yao-msft — APPROVED** [review]
:shipit:
