### PR TITLE
Test host for in-proc COM module validation

### LINKED ISSUE #5869: Access violation during process exit due to ComStaticStorageStatics
### Relevant area(s)

WinGet CLI, COM API

### Relevant command(s)

_No response_

### Brief description of your issue

It seems WinGet has [regressed from 1.10.320](https://github.com/microsoft/winget-cli/issues/5363) and is once again executing COM code during DLL uninitialization, when COM has already been unloaded.

### Steps to reproduce

I tried this code (complete project attached):

```cpp
int main()
{
	winrt::check_hresult(CoInitializeEx(nullptr, COINIT_MULTITHREADED));
	const struct Cleanup { ~Cleanup() { CoUninitialize();  } } cleanup;

	const auto packageManager{ CreateWinGetInstance<winget::PackageManager>(CLSID_PackageManager) };

	auto catalog = packageManager.GetPackageCatalogByName(L"winget");
	winrt::check_hresult(catalog.Connect().ExtendedErrorCode());
	return 0;
}

```

[WinGetBug-COM-AccessViolation.zip](https://github.com/user-attachments/files/23497544/WinGetBug-COM-AccessViolation.zip)

### Expected behavior

It works.

### Actual behavior

I get an access violation during process cleanup.

```
0:000> k
 # ChildEBP RetAddr      
00 (Inline) --------     WindowsPackageManager!winrt::impl::consume_Windows_ApplicationModel_Core_ICoreApplication<winrt::Windows::ApplicationModel::Core::ICoreApplication>::Properties+0xe [C:\__w\1\b\x86\Release\AppInstallerSharedLib\Generated Files\winrt\Windows.ApplicationModel.Core.h @ 86] 
01 (Inline) --------     WindowsPackageManager!winrt::Windows::ApplicationModel::Core::CoreApplication::Properties::__l2::<lambda_1>::operator()+0xe [C:\__w\1\b\x86\Release\AppInstallerSharedLib\Generated Files\winrt\Windows.ApplicationModel.Core.h @ 1082] 
02 (Inline) --------     WindowsPackageManager!winrt::impl::call_factory_cast+0x2a [C:\__w\1\b\x86\Release\AppInstallerSharedLib\Generated Files\winrt\base.h @ 6511] 
03 (Inline) --------     WindowsPackageManager!winrt::Windows::ApplicationModel::Core::CoreApplication::Properties+0x2a [C:\__w\1\b\x86\Release\AppInstallerSharedLib\Generated Files\winrt\Windows.ApplicationModel.Core.h @ 1082] 
04 00b3f590 621f40a3     WindowsPackageManager!AppInstaller::WinRT::COMStaticStorageStatics::ResetAll+0xd7 [C:\__w\1\s\external\pkg\src\AppInstallerSharedLib\COMStaticStorage.cpp @ 34] 
05 00b3f5b8 672d29c9     WindowsPackageManager!WindowsPackageManagerInProcModuleTerminate+0x63 [C:\__w\1\s\external\pkg\src\WindowsPackageManager\main.cpp @ 113] 
06 00b3f5c0 672d12b7     Microsoft_Management_Deployment_InProc!DllMain+0x29 [C:\__w\1\s\external\pkg\src\Microsoft.Management.Deployment.InProc\dllmain.cpp @ 32] 
07 00b3f600 672d139c     Microsoft_Management_Deployment_InProc!dllmain_dispatch+0x73 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\dll_dllmain.cpp @ 281] 
08 00b3f614 77168ff6     Microsoft_Management_Deployment_InProc!_DllMainCRTStartup+0x1c [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\dll_dllmain.cpp @ 334] 
09 00b3f634 771a0df3     ntdll!LdrxCallInitRoutine+0x16
0a 00b3f658 7712b11c     ntdll!LdrpCallInitRoutineInternal+0x22
0b 00b3f6a0 77127259     ntdll!LdrpCallInitRoutine+0xae
0c 00b3f740 771240fc     ntdll!LdrShutdownProcess+0x199
0d 00b3f810 7698b113     ntdll!RtlExitUserProcess+0x17c
WARNING: Stack unwind information not available. Following frames may be wrong.
0e 00b3f824 62caa464     KERNEL32!ExitProcess+0x13
0f 00b3f830 62caa40e     ucrtbased!wassert+0x534
10 00b3f868 62caa6d2     ucrtbased!wassert+0x4de
11 00b3f87c 007aa232     ucrtbased!exit+0x12
12 00b3f8dc 007aa0ad     WinGetBugTest!__scrt_common_main_seh+0x172 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 295] 
13 00b3f8e4 007aa458     WinGetBugTest!__scrt_common_main+0xd [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 331] 
14 00b3f8ec 76975d49     WinGetBugTest!mainCRTStartup+0x8 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp @ 17] 
15 00b3f8fc 7715d6db     KERNEL32!BaseThreadInitThunk+0x19
16 00b3f954 7715d661     ntdll!__RtlUserThreadStart+0x2b
17 00b3f964 00000000     ntdll!_RtlUserThreadStart+0x1b
```

### Environment

```shell
WinGet 1.12.350 from NuGet
```

### PR DESCRIPTION
**Pull request by JohnMcPMS**
Fixes #5869 and #5870 in the current code and will be backported to 1.12

## Change
Adds a test host that leverages the in-proc COM module (as built locally) to validate various lifetime management scenarios.  It has numerous options for controlling the scenarios, as well as an extensible model for adding different tests in the future.

It was able to hit the faults described in the linked issues, and the fixes are included:
- Move the `ServerShutdownSynchronization` to integrate with the signal monitoring directly, rather than registering as an object. This also means that there is no need to unregister, preventing the construction of a `TerminationSignalHandler`.
- Remove the call that terminates COM objects from the `DLL_PROCESS_DETACH` handler.  If the caller is using the module properly via COM, the `DllCanUnloadNow` calls should take care of things.  If the process is exiting without that call, leaking objects will be fine (the caller didn't uninitialize COM, so it is doubtful they care about a clean exit).

Additionally, these changes were made to support additional scenarios:
- Add the WinRT type names to the manifest file so that WinRT activation can work.
- Fix the activation factories to be counted objects for the module.
- Add a setting that allows the caller to prevent `DllCanUnloadNow` from checking the object state, always returning that it cannot unload now.  This can be used to prevent the module from being unloaded (and any active static objects alive) even if no external objects are active.

## Validation
The test host is run with various parameters as part of the E2E tests.
The linked issues are represented within the set of tests, as are several other scenarios.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-cli/pull/5910)

### CODE REVIEW

File: src/AppInstallerCLIE2ETests/InprocTestbedTests.cs [hunk 1]
```diff
@@ -0,0 +1,201 @@
...
+            {
+                ActivationType = ActivationType.ClassName,
+                ClearFactories = freeCachedFactories,
+                LeakCOM = leakCOM,
+                UnloadBehavior = unloadBehavior,
+                Iterations = 10,
+            });
+        }
+
+        private void RunInprocTestbed(TestbedParameters parameters, int timeout = 300000)
```
Comment (dkbennett) [inline src/AppInstallerCLIE2ETests/InprocTestbedTests.cs:144]: Might be nice to have default timeout constant defined, though it looks like this is the only place it is referenced. This 5m seems like a good number since we've seen other tests hit 2m randomly.

**Review by dkbennett — DISMISSED** [review]

File: src/ComInprocTestbed/ComInprocTestbed.manifest [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+			<!--<supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}" />-->
+
+			<!-- Windows 7 -->
+			<!--<supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}" />-->
+
+			<!-- Windows 8 -->
+			<!--<supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}" />-->
+
+			<!-- Windows 8.1 -->
+			<!--<supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}" />-->
```
Comment (florelis) [inline src/ComInprocTestbed/ComInprocTestbed.manifest:21]: nit: do we need to keep this part of the template?

File: src/ComInprocTestbed/ComInprocTestbed.vcxproj [hunk 3]
```diff
@@ -0,0 +1,223 @@
...
+    </ClCompile>
+  </ItemDefinitionGroup>
+  <ItemDefinitionGroup Condition="'$(Configuration)'=='Debug'">
+    <ClCompile>
+      <Optimization>Disabled</Optimization>
+      <PreprocessorDefinitions>_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
+      <TreatWarningAsError Condition="'$(Configuration)|$(Platform)'=='Debug|ARM64'">true</TreatWarningAsError>
+      <TreatWarningAsError Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">true</TreatWarningAsError>
+      <LanguageStandard Condition="'$(Configuration)|$(Platform)'=='Debug|ARM64'">stdcpp17</LanguageStandard>
+      <LanguageStandard Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">stdcpp17</LanguageStandard>
```
Comment (florelis) [inline src/ComInprocTestbed/ComInprocTestbed.vcxproj:106]:
```suggestion
      <TreatWarningAsError>true</TreatWarningAsError>
      <LanguageStandard>stdcpp17</LanguageStandard>
```

File: src/ComInprocTestbed/ComInprocTestbed.vcxproj [hunk 4]
```diff
@@ -0,0 +1,223 @@
...
+    <OutDir>$(SolutionDir)$(Platform)\$(Configuration)\$(ProjectName)\</OutDir>
+    <EmbedManifest>false</EmbedManifest>
+    <CopyLocalProjectReference>true</CopyLocalProjectReference>
+  </PropertyGroup>
+  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|ARM64'">
+    <LinkIncremental>false</LinkIncremental>
+    <OutDir>$(SolutionDir)$(Platform)\$(Configuration)\$(ProjectName)\</OutDir>
+    <EmbedManifest>false</EmbedManifest>
+    <CopyLocalProjectReference>true</CopyLocalProjectReference>
+  </PropertyGroup>
```
Comment (florelis) [inline src/ComInprocTestbed/ComInprocTestbed.vcxproj:78]:
```suggestion
  <PropertyGroup>
    <OutDir>$(SolutionDir)$(Platform)\$(Configuration)\$(ProjectName)\</OutDir>
    <OutDir Condition="'$(Platform)'=='Win32'">$(SolutionDir)x86\$(Configuration)\$(ProjectName)\</OutDir>
    <EmbedManifest>false</EmbedManifest>
    <CopyLocalProjectReference>true</CopyLocalProjectReference>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <LinkIncremental>true</LinkIncremental>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <LinkIncremental>false</LinkIncremental>
  </PropertyGroup>
```

File: src/ComInprocTestbed/ComInprocTestbed.vcxproj [hunk 5]
```diff
@@ -0,0 +1,223 @@
...
+    <Link>
+      <SubSystem>Console</SubSystem>
+      <GenerateWindowsMetadata>false</GenerateWindowsMetadata>
+    </Link>
+    <Manifest>
+      <AdditionalManifestFiles Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">ComInprocTestbed.manifest</AdditionalManifestFiles>
+    </Manifest>
+    <Manifest>
+      <AdditionalManifestFiles Condition="'$(Configuration)|$(Platform)'=='Debug|ARM64'">ComInprocTestbed.manifest</AdditionalManifestFiles>
+    </Manifest>
```
Comment (florelis) [inline src/ComInprocTestbed/ComInprocTestbed.vcxproj:118]:
```suggestion
    <Manifest>
      <AdditionalManifestFiles>ComInprocTestbed.manifest</AdditionalManifestFiles>
    </Manifest>
```

File: src/ComInprocTestbed/ComInprocTestbed.vcxproj [hunk 6]
```diff
@@ -0,0 +1,223 @@
...
+  <ItemDefinitionGroup Condition="'$(Platform)'=='Win32'">
+    <ClCompile>
+      <PreprocessorDefinitions>WIN32;%(PreprocessorDefinitions)</PreprocessorDefinitions>
+      <TreatWarningAsError Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">true</TreatWarningAsError>
+      <LanguageStandard Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">stdcpp17</LanguageStandard>
+    </ClCompile>
+    <Manifest>
+      <AdditionalManifestFiles Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">ComInprocTestbed.manifest</AdditionalManifestFiles>
+    </Manifest>
+  </ItemDefinitionGroup>
```
Comment (florelis) [inline src/ComInprocTestbed/ComInprocTestbed.vcxproj:129]:
```suggestion
  <ItemDefinitionGroup Condition="'$(Platform)'=='Win32'">
    <ClCompile>
      <PreprocessorDefinitions>WIN32;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ClCompile>
  </ItemDefinitionGroup>
```

File: src/ComInprocTestbed/ComInprocTestbed.vcxproj [hunk 7]
```diff
@@ -0,0 +1,223 @@
...
+      <Optimization>MaxSpeed</Optimization>
+      <FunctionLevelLinking>true</FunctionLevelLinking>
+      <IntrinsicFunctions>true</IntrinsicFunctions>
+      <PreprocessorDefinitions>NDEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
+      <TreatWarningAsError Condition="'$(Configuration)|$(Platform)'=='Release|ARM64'">true</TreatWarningAsError>
+      <TreatWarningAsError Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">true</TreatWarningAsError>
+      <TreatWarningAsError Condition="'$(Configuration)|$(Platform)'=='Release|x64'">true</TreatWarningAsError>
+      <LanguageStandard Condition="'$(Configuration)|$(Platform)'=='Release|ARM64'">stdcpp17</LanguageStandard>
+      <LanguageStandard Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">stdcpp17</LanguageStandard>
+      <LanguageStandard Condition="'$(Configuration)|$(Platform)'=='Release|x64'">stdcpp17</LanguageStandard>
```
Comment (florelis) [inline src/ComInprocTestbed/ComInprocTestbed.vcxproj:141]:
```suggestion
      <TreatWarningAsError>true</TreatWarningAsError>
      <LanguageStandard>stdcpp17</LanguageStandard>
```

File: src/ComInprocTestbed/ComInprocTestbed.vcxproj [hunk 8]
```diff
@@ -0,0 +1,223 @@
...
+  <ItemGroup>
+    <ClCompile Include="main.cpp" />
+    <ClCompile Include="PackageManager.cpp" />
+    <ClCompile Include="pch.cpp">
+      <PrecompiledHeader Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">Create</PrecompiledHeader>
+      <PrecompiledHeader Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">Create</PrecompiledHeader>
+      <PrecompiledHeader Condition="'$(Configuration)|$(Platform)'=='Debug|ARM64'">Create</PrecompiledHeader>
+      <PrecompiledHeader Condition="'$(Configuration)|$(Platform)'=='Release|ARM64'">Create</PrecompiledHeader>
+      <PrecompiledHeader Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">Create</PrecompiledHeader>
+      <PrecompiledHeader Condition="'$(Configuration)|$(Platform)'=='Release|x64'">Create</PrecompiledHeader>
```
Comment (florelis) [inline src/ComInprocTestbed/ComInprocTestbed.vcxproj:168]:
```suggestion
      <PrecompiledHeader>Create</PrecompiledHeader>
```

File: src/ComInprocTestbed/ComInprocTestbed.vcxproj [hunk 9]
```diff
@@ -0,0 +1,223 @@
...
+    </Link>
+    <Manifest>
+      <AdditionalManifestFiles Condition="'$(Configuration)|$(Platform)'=='Release|ARM64'">ComInprocTestbed.manifest</AdditionalManifestFiles>
+    </Manifest>
+    <Manifest>
+      <AdditionalManifestFiles Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">ComInprocTestbed.manifest</AdditionalManifestFiles>
+    </Manifest>
+    <Manifest>
+      <AdditionalManifestFiles Condition="'$(Configuration)|$(Platform)'=='Release|x64'">ComInprocTestbed.manifest</AdditionalManifestFiles>
+    </Manifest>
```
Comment (florelis) [inline src/ComInprocTestbed/ComInprocTestbed.vcxproj:157]:
```suggestion
    <Manifest>
      <AdditionalManifestFiles>ComInprocTestbed.manifest</AdditionalManifestFiles>
    </Manifest>
```

File: src/AppInstallerCLIE2ETests/InprocTestbedTests.cs [hunk 10]
```diff
@@ -0,0 +1,200 @@
...
+        /// </summary>
+        [OneTimeSetUp]
+        public void OneTimeSetup()
+        {
+            this.InprocTestbedPath = TestSetup.Parameters.InprocTestbedPath;
+
+            if (string.IsNullOrWhiteSpace(this.InprocTestbedPath))
+            {
+                string assemblyLocation = Assembly.GetExecutingAssembly().Location;
+                this.InprocTestbedPath = Path.Join(Path.GetDirectoryName(assemblyLocation), "..\\ComInprocTestbed\\ComInprocTestbed.exe");
```
Comment (florelis) [inline src/AppInstallerCLIE2ETests/InprocTestbedTests.cs:78]: Isn't there something like a `TestContext.TestDirectory`?

File: src/ComInprocTestbed/Tests.cpp [hunk 11]
```diff
@@ -0,0 +1,602 @@
+// Copyright (c) Microsoft Corporation.
```
Comment (florelis) [inline src/ComInprocTestbed/Tests.cpp:1]: (I'll admit that I didn't read this file very closely...)
