### PR TITLE
Fix file overwrite warning displayed on clean first install

### LINKED ISSUE #2327: File Overwrite Warning on First Install of Portable App
### Brief description of your issue

When first installing a Portable App, there is a warning displayed that a file is being overwritten, even though it is a clean install (running in windows sandbox)

### Steps to reproduce

Unzip the manifest attached; 
Install the manifest locally using v1.3 of the winget client

Manifest Files: [OO-Software.zip](https://github.com/microsoft/winget-cli/files/9093714/OO-Software.zip)
Log Files: [OO-Software.ShutUp10.zip](https://github.com/microsoft/winget-cli/files/9093744/Logs.for.OO-Software.ShutUp10.zip)

### Expected behavior

No Warning to be shown, as that file shouldn't exist from a clean sandbox install.
<details>
<summary>Expected Command Line Output from Install</summary>

```
--> Installing WinGet
Tip: you can type 'Update-EnvironmentVariables' to update your environment variables, such as after installing a new software.

--> Configuring Winget
Admin setting enabled.

--> Installing the Manifest 1.9.1431.368

Found ShutUp10++ [OO-Software.ShutUp10] Version 1.9.1431.368
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dl5.oo-software.com/files/ooshutup10/OOSU10.exe
  ██████████████████████████████  1.58 MB / 1.58 MB
Successfully verified installer hash
Starting package install...
Path environment variable modified; restart your shell to use the new value.
Successfully installed

--> Refreshing environment variables

--> Comparing ARP Entries

DisplayName    DisplayVersion Publisher    ProductCode
-----------    -------------- ---------    -----------
O&O ShutUp10++ 1.9.1431       O&O Software OO-Software.ShutUp10__DefaultSource
```
</details>

### Actual behavior

There is a warning shown - 
> Overwriting existing file:C:\Users\WDAGUtilityAccount\AppData\Local\Microsoft\WinGet\Links\shutup10.exe
<details>
<summary>Command Line Output from Install</summary>

```
--> Installing WinGet
Tip: you can type 'Update-EnvironmentVariables' to update your environment variables, such as after installing a new software.

--> Configuring Winget
Admin setting enabled.

--> Installing the Manifest 1.9.1431.368

Found ShutUp10++ [OO-Software.ShutUp10] Version 1.9.1431.368
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dl5.oo-software.com/files/ooshutup10/OOSU10.exe
  ██████████████████████████████  1.58 MB / 1.58 MB
Successfully verified installer hash
Starting package install...
Overwriting existing file:C:\Users\WDAGUtilityAccount\AppData\Local\Microsoft\WinGet\Links\shutup10.exe
Path environment variable modified; restart your shell to use the new value.
Successfully installed

--> Refreshing environment variables

--> Comparing ARP Entries

DisplayName    DisplayVersion Publisher    ProductCode
-----------    -------------- ---------    -----------
O&O ShutUp10++ 1.9.1431       O&O Software OO-Software.ShutUp10__DefaultSource
```

</details>
<details>
<summary>Screen Capture from Install</summary>

image

</details>

### Environment

```shell
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget --info
Windows Package Manager v1.3.1872
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.1766
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.1872.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### PR DESCRIPTION
**Pull request by ryfu-msft**
Fixes #2327 

Changes:
Fixes a big where the file overwrite warning was shown on every install including clean first installs. Modified the logic so that the warning only shows if a file is removed.

Tests:
Added an E2E test that installs a portable package twice. Verifies that the warning is only shown during the second install and not the first.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-cli/pull/2375)

### CODE REVIEW

File: src/AppInstallerCLICore/Workflows/PortableFlow.cpp [hunk 1]
```diff
@@ -428,10 +428,10 @@ namespace AppInstaller::CLI::Workflow
                 AICLI_LOG(CLI, Info, << "Unable to create symlink. '" << symlinkFullPath << "points to an existing directory.");
                 AICLI_TERMINATE_CONTEXT(APPINSTALLER_CLI_ERROR_PORTABLE_SYMLINK_PATH_IS_DIRECTORY);
             }
-            else
+            else if (std::filesystem::remove(symlinkFullPath))
```
Comment (JohnMcPMS) [inline src/AppInstallerCLICore/Workflows/PortableFlow.cpp:431]: I assume that `create_symlink` doesn't allow overwriting an existing symlink?  It isn't clear what will happen from either location I looked at, but I would guess that it doesn't.

**Review by JohnMcPMS — APPROVED** [review]

File: src/AppInstallerCLICore/Workflows/PortableFlow.cpp (hunk 1 above)
Comment (ryfu-msft) [reply src/AppInstallerCLICore/Workflows/PortableFlow.cpp:431]: Yes that's right. If we don't remove the existing file, `create_symlink` will fail and throw and error that the "file already exists"
